FROM amd64/python:3.7-slim-buster

WORKDIR /app

COPY requirements.txt ./

RUN apt-get update
RUN apt-get upgrade -y

RUN apt-get clean && apt-get update && apt-get install ffmpeg libsm6 libxext6  -y

RUN pip install -r requirements.txt

COPY . .

CMD [ "python3", "-u", "./main.py" ]